### ISSUE TITLE
复现结果存在差异

### ISSUE THREAD

**Issue by JinlingLiCode** [Linfeng-Tang/Evaluation-for-Image-Fusion#1]
博主您好！在使用您matlab代码复现评价指标时，发现SD    VIF   SCD   SF  四个指标与作者结果存在差异 ，其中matlab版本为2019b

**Comment by JinlingLiCode** [comment]
![image](https://github.com/Linfeng-Tang/Evaluation-for-Image-Fusion/assets/67734931/fba8e39f-148a-4f33-86b8-b6f04156ad1e)

**Comment by Linfeng-Tang** [comment]
作者的结果是哪一个的呢 主要是与数据类型有关 最开始数据类型使用的是uint8型 会出现截断的情况 后面换成了floate型 就不会出现数据截断的问题了
