### ISSUE TITLE
Matlab or Python

### ISSUE THREAD

**Issue by Rashfu** [Linfeng-Tang/Evaluation-for-Image-Fusion#3]
您好，我看到您在csdn上也放出了python版本的评估代码。想请教您推荐哪一个语言来评估算法性能呢？（matlab用来评估几个未复现的特征互信息指标，其他的用python吗？）

**Comment by Linfeng-Tang** [comment]
我最初是使用的MATLAB来评估的 后面基本上换成了Python版本的，Python版本对于文件处理比MATLAB版本更加方便一些。

**Comment by yaoliu0803** [comment]
> 您好，我看到您在csdn上也放出了python版本的评估代码。想请教您推荐哪一个语言来评估算法性能呢？（matlab用来评估几个未复现的特征互信息指标，其他的用python吗？）

你好，请问能分享一下python版本的评价指标链接吗？谢谢

**Comment by Rashfu** [comment]
@yaoliu0803 你可以在这里找到相关代码 https://blog.csdn.net/fovever_/article/details/129332278
